// <auto-generated />
using System;
using Bfn.DevOps.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bfn.DevOps.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260930201417_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("Bfn.DevOps.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<string>("Client")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1007);

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1008);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1002)
                        .HasDefaultValueSql("'1970-01-01 00:00:00'");

                    b.Property<string>("CreUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1001);

                    b.Property<DateTime?>("DelDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1006);

                    b.Property<string>("DelUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1005);

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnOrder(1009);

                    b.Property<bool>("IsFounder")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(6);

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1004);

                    b.Property<string>("ModUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1003);

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(8);

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(10);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(11);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(12);

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(13);

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(14);

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(15);

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(16);

                    b.Property<string>("UId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1000)
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(17);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("SyUser", (string)null);
                });

            modelBuilder.Entity("Bfn.DevOps.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Client")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1007);

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1008);

                    b.Property<DateTime>("CreDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1002)
                        .HasDefaultValueSql("'1970-01-01 00:00:00'");

                    b.Property<string>("CreUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1001);

                    b.Property<DateTime?>("DelDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1006);

                    b.Property<string>("DelUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1005);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnOrder(1009);

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1004);

                    b.Property<string>("ModUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1003);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<string>("UId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1000)
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Bfn.DevOps.Models.BoardCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("AssignedAgentId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("AssignedUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("AttachmentLabel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<int>("BoardColumnId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<string>("Client")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1007);

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1008);

                    b.Property<DateTime>("CreDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1002)
                        .HasDefaultValueSql("'1970-01-01 00:00:00'");

                    b.Property<string>("CreUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1001);

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("DelDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1006);

                    b.Property<string>("DelUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1005);

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnOrder(1009);

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1004);

                    b.Property<string>("ModUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1003);

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Unspecified")
                        .HasColumnOrder(9);

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(10);

                    b.Property<string>("Tags")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(11);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(12);

                    b.Property<string>("UId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1000)
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("BoardColumnId", "SortOrder");

                    b.ToTable("BoardCards");
                });

            modelBuilder.Entity("Bfn.DevOps.Models.BoardCardComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("AuthorId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("AuthorUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<int>("BoardCardId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<string>("Client")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1007);

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1008);

                    b.Property<DateTime>("CreDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1002)
                        .HasDefaultValueSql("'1970-01-01 00:00:00'");

                    b.Property<string>("CreUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1001);

                    b.Property<DateTime?>("DelDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1006);

                    b.Property<string>("DelUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1005);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnOrder(1009);

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1004);

                    b.Property<string>("ModUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1003);

                    b.Property<string>("UId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1000)
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("BoardCardId", "CreDate");

                    b.ToTable("BoardCardComments");
                });

            modelBuilder.Entity("Bfn.DevOps.Models.BoardCardSubtask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int>("BoardCardId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<string>("Client")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1007);

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1008);

                    b.Property<DateTime>("CreDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1002)
                        .HasDefaultValueSql("'1970-01-01 00:00:00'");

                    b.Property<string>("CreUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1001);

                    b.Property<DateTime?>("DelDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1006);

                    b.Property<string>("DelUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1005);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnOrder(1009);

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1004);

                    b.Property<string>("ModUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1003);

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<string>("UId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1000)
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'");

                    b.HasKey("Id");

                    b.HasIndex("BoardCardId", "SortOrder");

                    b.ToTable("BoardCardSubtasks");
                });

            modelBuilder.Entity("Bfn.DevOps.Models.BoardColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int>("BoardId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<string>("Client")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1007);

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1008);

                    b.Property<DateTime>("CreDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1002)
                        .HasDefaultValueSql("'1970-01-01 00:00:00'");

                    b.Property<string>("CreUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1001);

                    b.Property<DateTime?>("DelDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1006);

                    b.Property<string>("DelUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1005);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnOrder(1009);

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1004);

                    b.Property<string>("ModUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1003);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<string>("UId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1000)
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "SortOrder");

                    b.ToTable("BoardColumns");
                });

            modelBuilder.Entity("Bfn.DevOps.Models.DeploymentRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Client")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1007);

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1008);

                    b.Property<DateTime>("CreDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1002)
                        .HasDefaultValueSql("'1970-01-01 00:00:00'");

                    b.Property<string>("CreUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1001);

                    b.Property<DateTime?>("DelDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1006);

                    b.Property<string>("DelUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1005);

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnOrder(1009);

                    b.Property<string>("Log")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1004);

                    b.Property<string>("ModUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1003);

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<string>("UId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1000)
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("DeploymentRuns");
                });

            modelBuilder.Entity("Bfn.DevOps.Models.DeploymentRunStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Client")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1007);

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1008);

                    b.Property<DateTime>("CreDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1002)
                        .HasDefaultValueSql("'1970-01-01 00:00:00'");

                    b.Property<string>("CreUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1001);

                    b.Property<DateTime?>("DelDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1006);

                    b.Property<string>("DelUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1005);

                    b.Property<int>("DeploymentRunId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("DeploymentStepId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnOrder(1009);

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1004);

                    b.Property<string>("ModUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1003);

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("UId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1000)
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentStepId");

                    b.HasIndex("DeploymentRunId", "DeploymentStepId")
                        .IsUnique();

                    b.ToTable("DeploymentRunSteps");
                });

            modelBuilder.Entity("Bfn.DevOps.Models.DeploymentStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Client")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1007);

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1008);

                    b.Property<bool>("ContinueOnError")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1002)
                        .HasDefaultValueSql("'1970-01-01 00:00:00'");

                    b.Property<string>("CreUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1001);

                    b.Property<DateTime?>("DelDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1006);

                    b.Property<string>("DelUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1005);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnOrder(1009);

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1004);

                    b.Property<string>("ModUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1003);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(4);

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(6);

                    b.Property<int>("StepTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(7);

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(8);

                    b.Property<string>("UId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1000)
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'");

                    b.HasKey("Id");

                    b.HasIndex("StepTypeId");

                    b.HasIndex("ProjectId", "SortOrder");

                    b.ToTable("DeploymentSteps");
                });

            modelBuilder.Entity("Bfn.DevOps.Models.DevOpsProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("ApplicationPoolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Client")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1007);

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1008);

                    b.Property<DateTime>("CreDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1002)
                        .HasDefaultValueSql("'1970-01-01 00:00:00'");

                    b.Property<string>("CreUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1001);

                    b.Property<DateTime?>("DelDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1006);

                    b.Property<string>("DelUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1005);

                    b.Property<string>("Environment")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Dev")
                        .HasColumnOrder(2);

                    b.Property<string>("IisSiteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnOrder(1009);

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1004);

                    b.Property<string>("ModUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1003);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<string>("RepositoryUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("UId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1000)
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<string>("WorkingDirectory")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<bool>("ZeroDowntimeEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(8);

                    b.HasKey("Id");

                    b.HasIndex("Name", "Environment")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Bfn.DevOps.Models.StepType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Client")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1007);

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1008);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1002)
                        .HasDefaultValueSql("'1970-01-01 00:00:00'");

                    b.Property<string>("CreUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1001);

                    b.Property<DateTime?>("DelDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1006);

                    b.Property<string>("DelUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1005);

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnOrder(1009);

                    b.Property<DateTime?>("ModDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1004);

                    b.Property<string>("ModUser")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1003);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(4);

                    b.Property<string>("UId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1000)
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("StepTypes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("SyRole", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("SyUserLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("SyUserRole", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("SyUserToken", (string)null);
                });

            modelBuilder.Entity("Bfn.DevOps.Models.BoardCard", b =>
                {
                    b.HasOne("Bfn.DevOps.Models.ApplicationUser", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bfn.DevOps.Models.BoardColumn", "Column")
                        .WithMany("Cards")
                        .HasForeignKey("BoardColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bfn.DevOps.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedUser");

                    b.Navigation("Column");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Bfn.DevOps.Models.BoardCardComment", b =>
                {
                    b.HasOne("Bfn.DevOps.Models.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bfn.DevOps.Models.BoardCard", "Card")
                        .WithMany("Comments")
                        .HasForeignKey("BoardCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Bfn.DevOps.Models.BoardCardSubtask", b =>
                {
                    b.HasOne("Bfn.DevOps.Models.BoardCard", "Card")
                        .WithMany("Subtasks")
                        .HasForeignKey("BoardCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Bfn.DevOps.Models.BoardColumn", b =>
                {
                    b.HasOne("Bfn.DevOps.Models.Board", "Board")
                        .WithMany("Columns")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Bfn.DevOps.Models.DeploymentRun", b =>
                {
                    b.HasOne("Bfn.DevOps.Models.DevOpsProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Bfn.DevOps.Models.DeploymentRunStep", b =>
                {
                    b.HasOne("Bfn.DevOps.Models.DeploymentRun", "Run")
                        .WithMany("StepRuns")
                        .HasForeignKey("DeploymentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bfn.DevOps.Models.DeploymentStep", "Step")
                        .WithMany()
                        .HasForeignKey("DeploymentStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("Bfn.DevOps.Models.DeploymentStep", b =>
                {
                    b.HasOne("Bfn.DevOps.Models.DevOpsProject", "Project")
                        .WithMany("DeploymentSteps")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bfn.DevOps.Models.StepType", "StepType")
                        .WithMany()
                        .HasForeignKey("StepTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("StepType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Bfn.DevOps.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bfn.DevOps.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Bfn.DevOps.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bfn.DevOps.Models.Board", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("Bfn.DevOps.Models.BoardCard", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Subtasks");
                });

            modelBuilder.Entity("Bfn.DevOps.Models.BoardColumn", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Bfn.DevOps.Models.DeploymentRun", b =>
                {
                    b.Navigation("StepRuns");
                });

            modelBuilder.Entity("Bfn.DevOps.Models.DevOpsProject", b =>
                {
                    b.Navigation("DeploymentSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
